logging:
  level.root: DEBUG

server:
  port: 9092

spring:
  application:
    name: gateway-service
  profiles:
    active: gateway
  config:
    import: 'configserver:'
  cloud:
    config:
      name: gateway-service,config-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

log:
  app-name: gateway-service