spring:
  application:
    name: kafka-stream-service
  profiles:
    active: kafka_stream
  config:
    import: 'configserver:'
  cloud:
    config:
      name: kafka-stream-service,config-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

log:
  app-name: kafka-stream-service