spring:
  application:
    name: analytics-service
  profiles:
    active: analytics
  config:
    import: 'configserver:'
  cloud:
    config:
      name: analytics-service,config-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

log:
  app-name: analytics-service