server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aniket18/spring-cloud-config-server-repository
          default-label: main
          username: aniket18
          password: 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
          clone-on-start: true
    fail-fast: true
    security:
      user:
        name: spring_cloud_user
        password: springCloud_Pwd!